version: '3.8'

networks:
  internal_services:
  accounts:

services:
  accounts-mongodb:
    container_name: trashify-accounts-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_ACCOUNTS_DATABASE}
    volumes:
      - trashify-accounts-mongodb:/data/db
    command: mongod --port ${MONGODB_ACCOUNTS_PORT}
    restart: unless-stopped
    networks:
      - accounts
    ports: 
      - ${MONGODB_ACCOUNTS_PORT}:${MONGODB_ACCOUNTS_PORT}
    expose:
      - ${MONGODB_ACCOUNTS_PORT}


  accounts-service:
    container_name: trashify-accounts-service
    build:
      context: .
      dockerfile: ./apps/accounts-service/Dockerfile
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    depends_on:
      - accounts-mongodb
    restart: unless-stopped
    networks:
      - internal_services
      - accounts

volumes:
  trashify-accounts-mongodb: