output "api_gateway_host" {
  value       = module.api-gateway.application_url
  description = "The api gateway host."
}

output "accounts_service_host" {
  value       = module.accounts-service.application_url
  description = "The accounts service host."
}

output "resource_group" {
  value       = azurerm_resource_group.main.name
  description = "The resource group."
}

output "api_gateway_name" {
  value       = module.api-gateway.application_caf_name
  description = "The api gateway name generated by the Azure Cloud Adoption Framework."
}

output "accounts_service_name" {
  value       = module.accounts-service.application_caf_name
  description = "The accounts service name generated by the Azure Cloud Adoption Framework."
}

output "api_gateway_container_registry_name" {
  value       = module.api-gateway.container_registry_name
  description = "The api gateway Docker Container Registry name generated by the Azure Cloud Adoption Framework."
}

output "accounts_service_container_registry_name" {
  value       = module.accounts-service.container_registry_name
  description = "The accounts service Docker Container Registry name generated by the Azure Cloud Adoption Framework."
}
