output "accounts_service_host" {
  value       = module.accounts-service.application_url
  description = "The accounts service host."
}

output "trash_service_host" {
  value       = module.trash-service.application_url
  description = "The trash service host."
}

output "mailing_service_host" {
  value       = module.mailing-service.application_url
  description = "The mailing service host."
}

output "api_gateway_service_host" {
  value       = module.api-gateway-service.application_url
  description = "The API gateway service host."
}

output "resource_group" {
  value       = azurerm_resource_group.main.name
  description = "The resource group."
}

output "accounts_service_name" {
  value       = module.accounts-service.application_caf_name
  description = "The accounts service name generated by the Azure Cloud Adoption Framework."
}

output "mailing_service_name" {
  value       = module.mailing-service.application_caf_name
  description = "The mailing service name generated by the Azure Cloud Adoption Framework."
}

output "api_gateway_service_name" {
  value       = module.api-gateway-service.application_caf_name
  description = "The API gateway service name generated by the Azure Cloud Adoption Framework."
}


