#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3)

if [ "$branch_name" != "HEAD:changeset-release/main" ]; then
  yarn test:ci
else
  echo "Skipping tests for branch $branch_name"
fi
