name: 'production-docs-pull-request-checks'

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/adrs/**"
      - "docs/backend/**"
      - "docs/eng-degree-docs/**"
      - "docs/frontend/**"
      - ".github/workflows/production-docs-pull-request-checks.yml"
      
jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Engineering Degree compilation check
        uses: xu-cheng/texlive-action/full@v1
        run: cd docs/eng-degree-docs/eng-degree & pdflatex  eng-degree.tex
      - name: Engineering Degree compilation check
        uses: xu-cheng/texlive-action/full@v1
        run: cd docs/eng-degree-docs/work-schedule & pdflatex  work-schedule.tex


