name: 'production-accounts-microservice-deployment'

on:
  push:
    branches:
      - main
    paths:
      - "apps/accounts-service/**"
      - ".github/workflows/production-accounts-microservice-deployment.yml"
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://crtrashifyproduction.azurecr.io/
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Creating .npmrc
      run: |
        cat << EOF > "$HOME/.npmrc"
          @trashify:registry=https://registry.npmjs.org/
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
        EOF
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: crtrashifyproduction.azurecr.io/${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/trashify-accounts-service:${{ github.sha }}
        file: ./apps/accounts-service/Dockerfile
        target: production
      env:
        NODE_ENV: production
        ACCOUNTS_SERVICE_URL: ${{ secrets.ACCOUNTS_SERVICE_URL }}

  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-trashify-accounts-service-production'
        slot-name: 'production'
        publish-profile: ${{ secrets.ACCOUNTS_SERVICE_PUBLISH_PROFILE }}
        images: 'crtrashifyproduction.azurecr.io/${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/trashify-accounts-service:${{ github.sha }}'
