name: 'production-accounts-microservice-deployment'

on:
  push:
    branches:
      - main
    paths:
      - "apps/accounts-service/**"
      - ".github/workflows/production-accounts-microservice-deployment.yml"
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://crtrashifyproduction.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_59bcc498a3474f9da508ebe4069eeed2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_50018a37ed75496da003f100926f11a2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: crtrashifyproduction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_59bcc498a3474f9da508ebe4069eeed2 }}/crtrashifyproduction/trashify-accounts-service:${{ github.sha }}
        file: ./apps/accounts-service/Dockerfile
      env:
        ACCOUNTS_SERVICE_URL: ${{ secrets.ACCOUNTS_SERVICE_URL }}

  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-trashify-accounts-service-production'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_751af0fdf22a4ad8b2f9b296ed9f6ac4 }}
        images: 'crtrashifyproduction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_59bcc498a3474f9da508ebe4069eeed2 }}/crtrashifyproduction/trashify-accounts-service:${{ github.sha }}'