name: 'production-mailing-microservice-deployment'

on:
  push:
    branches:
      - main
    paths:
      - "apps/mailing-service/**"
      - ".github/workflows/production-mailing-microservice-deployment.yml"
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://crtrashifyproduction.azurecr.io/
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: crtrashifyproduction.azurecr.io/${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/trashify-mailing-service:${{ github.sha }}
        file: ./apps/mailing-service/Dockerfile
        target: production
        build-args: |
          NPM_READ_TOKEN=${{ secrets.NPM_READ_TOKEN }}
          MAILING_SERVICE_URL=${{ secrets.MAILING_SERVICE_URL }}
      env:
        NODE_ENV: production

  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-trashify-mailing-service-production'
        slot-name: 'production'
        publish-profile: ${{ secrets.MAILING_SERVICE_PUBLISH_PROFILE }}
        images: 'crtrashifyproduction.azurecr.io/${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/trashify-mailing-service:${{ github.sha }}'
